interface Student {
  id: string;
  name: string;
  avatar: string;
  records: Record<string, AttendanceStatus>;
}
type AttendanceStatus = 'P' | 'A' | 'L' | 'WK' | 'HL' | 'CL' | 'PL';

export const students: Student[] = [
  {
    id: '27',
    name: 'ALI HAMZA',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '27',
    name: 'ALI HAMZA',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '27',
    name: 'ALI HAMZA',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '27',
    name: 'ALI HAMZA',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '1',
    name: 'Umair Abid',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '2',
    name: 'Waleed Abdullah',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'WK',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '3',
    name: 'Zubaida bibi',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
    },
  },
  {
    id: '4',
    name: 'Muhammad Sufyan',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'WK',
      '6': 'P',
      '7': 'P',
      '8': 'A',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '5',
    name: 'Nimra Rasheed',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'WK',
    },
  },
  {
    id: '6',
    name: 'Fakhra-E-Sadia',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '7',
    name: 'Usama Javed',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
    },
  },
  {
    id: '8',
    name: 'Sidra Anwar',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'WK',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '9',
    name: 'Muhammad IRFAN',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'WK',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '10',
    name: 'Shahzaib',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'WK',
      '9': 'P',
      '10': 'P',
    },
  },
  {
    id: '11',
    name: 'Maryam Naveed',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '12',
    name: 'Ansa Saleem',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'P',
      '8': 'A',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '13',
    name: 'Azan Sagheer',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'WK',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '14',
    name: 'Ali Hussnain',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'P',
      '7': 'WK',
      '8': 'P',
      '9': 'P',
      '10': 'A',
      // rest of the month
    },
  },
  {
    id: '15',
    name: 'Humna Mustafa',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '16',
    name: 'Muhammad Ramzan',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '17',
    name: 'Ayesha Sajid',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'A',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '18',
    name: 'Tehreem Imran',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'WK',
      '8': 'A',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '19',
    name: 'Nimra Akram',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'P',
      '4': 'P',
      '5': 'A',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'P',
      '10': 'A',
      // rest of the month
    },
  },
  {
    id: '20',
    name: 'Naila Parveen',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'A',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '21',
    name: 'Sadaat Sajid',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'P',
      '10': 'A',
      // rest of the month
    },
  },
  {
    id: '22',
    name: 'Tajammal Hussain',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'A',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '23',
    name: 'M. Zohaib AsIam',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '24',
    name: 'Zohra Shahid',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'A',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '25',
    name: 'Zaheer Abass',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'A',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '26',
    name: 'Aliza Anwar',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'A',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '27',
    name: 'ALI HAMZA',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '28',
    name: 'Uzair Shafqat',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'P',
      '3': 'P',
      '4': 'A',
      '5': 'P',
      '6': 'WK',
      '7': 'P',
      '8': 'P',
      '9': 'A',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '29',
    name: 'Umair Shahzad',
    avatar: '/images/ali.png',
    records: {
      '1': 'P',
      '2': 'A',
      '3': 'P',
      '4': 'P',
      '5': 'P',
      '6': 'WK',
      '7': 'A',
      '8': 'P',
      '9': 'P',
      '10': 'P',
      // rest of the month
    },
  },
  {
    id: '30',
    name: 'Areeba Zafar',
    avatar: '/images/ali.png',
    records: {
      '1': 'A',
      '2': 'P',
      '3': 'A',
      '4': 'P',
      '5': 'P',
      '6': 'P',
      '7': 'A',
      '8': 'P',
      '9': 'WK',
      '10': 'P',
      // rest of the month
    },
  }

];
